service: my-react-playground-backend-csharp-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: dotnetcore3.1
  lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: my_serverless

package:
  individually: true

functions:
# the line below is function name
  get-all-collections:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::GetCollections
    package:
      artifact: bin/Release/netcoreapp3.1/collections-api.zip
    events:
      - httpApi:
          path: /collections
          method: get
  get-collection:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::GetCollectionById
    package:
      artifact: bin/Release/netcoreapp3.1/collections-api.zip
    events:
      - httpApi:
          path: /collection/{paramId}
          method: get
