service: my-react-playground-backend-csharp-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: dotnetcore3.1
  lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: my_serverless
  environment: 
# these are injected into c# files, taken from the config file. The var name at the beginning of the line is available in c#, doesnt have to be same as in config file, but can be for consistency
    DB_HOST: ${file(./config.dev.json):DB_HOST}
    DB_NAME: ${file(./config.dev.json):DB_NAME}
    DB_USER: ${file(./config.dev.json):DB_USER}
    DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}

package:
  individually: true

functions:
# the line below is serverless function name. C# function name is in handler.
  get-all-collections:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::GetCollections
    package:
      artifact: bin/Release/netcoreapp3.1/collections-api.zip
    events:
      - httpApi:
          path: /collections
          method: get
  get-collection:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::GetCollectionById
    package:
      artifact: bin/Release/netcoreapp3.1/collections-api.zip
    events:
      - httpApi:
          path: /collection/{paramId}
          method: get
  create-collection:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::CreateCollection
    package:
      artifact: bin/Release/netcoreapp3.1/collections-api.zip
    events:
      - httpApi:
          path: /collection/{paramId}
          method: post
